fail-on-severity: low
fail-on-scopes:
  - runtime
  - development
  - unknown
vulnerability-check: true
license-check: true
warn-only: false
show-openssf-scorecard: true
warn-on-openssf-scorecard-level: 5
show-patched-versions: true
retry-on-snapshot-warnings: true
retry-on-snapshot-warnings-timeout: 180
deny-licenses:
  - AGPL-3.0-only
  - AGPL-3.0-or-later
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-3.0-only
  - GPL-3.0-or-later
